name: flutter_facebook_appevents
description: flutter_facebook_appevents integrates Facebook App Events to your Flutter app.
version: 0.2.0
author: zonble <zonble@gmail.com>
homepage: https://github.com/zonble/flutter_facebook_appevents

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kkbox.flutter_facebook_appevents
        pluginClass: FlutterFacebookAppeventsPlugin
      ios:
        pluginClass: FlutterFacebookAppeventsPlugin
