name: flutter_facebook_appevents
description: Bridges Facebook events.
version: 0.1.0
author: Weizhong Yang a.k.a zonble <zonble@gmail.com>
homepage: https://github.com/KKBOX/flutter_facebook_appevents

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.kkbox.flutter_facebook_appevents
    pluginClass: FlutterFacebookAppeventsPlugin
